### ISSUE TITLE
htmlNodes is Null

### ISSUE THREAD

**Issue by frahman2** [maryna-b/ParseWeb-AgilityPack#1]
Hi,

While running the code the value of the htmlNodes and htmlNodes2 is always null for a reason I do not know. I have just updated the Refrence of the HAP to the latest version.

Please any advise.

**Comment by frahman2** [comment]
It was Proxy Issue

**Comment by maryna-b** [comment]
Hello. I have just got the same error, though it didn't appear before. I made a commit with the solution, in case you are interested.

**Comment by frahman2** [comment]
Hi,

Thank you, that was an issue because of the proxy Authentication.
